spring:
  application:
    name: PortalCommonApi  # Service registers under this name
  security:
    username: admin
    password: openpaasta
  main:
    allow-bean-definition-overriding: true
#    web-application-type: none
server:
  port: ${PORT:2223}   # HTTP (Tomcat) port

datasource:
  hikari:
    minimumIdle: 50
    idleTimeout: 10000
    connectionTimeout: 30000
    validationTimeout: 5000
    maxLifetime: 1000
    maximumPoolSize: 50
    autoCommit: true
  cc:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/cloud_controller
    username: ccadmin # YOUR CC DB STORAGE ACCOUNT
    password: 'PASSWORD' # YOUR CC DB PASSWORD
  portal:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/portaldb
    username: root # YOUR UAA PORTAL DB ACCOUNT
    password: 'PASSWORD' # YOUR PORTAL DB PASSWORD
  uaa:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/uaa
    username: uaaadmin # YOUR UAA DB ACCOUNT
    password: 'PASSWORD' # YOUR UAA DB PASSWORD
jpa:
  database: mysql
  show-sql: true
  hibernate:
    ddl-auto: none
    naming:
      strategy: org.hibernate.dialect.MySQL5Dialect
  generate-ddl: false
mail:
  smtp:
    host: smtp.gmail.com
    port: 465
    username: PaaS-TA # YOUR ACCOUNT
    password: 'PASSWORD' # YOUR PAAS-TA PASSWORD
    useremail: openpasta@gmail.com
    properties:
      auth: true
      starttls:
        enable: true
        required: true
      maximumTotalQps: 90
      authUrl: http://XXX.XXX.XXX.XXX  # YOUR AUTH URL
      imgUrl: http://XXX.XXX.XXX.XXX:8080/v1/KEY_84586dfdc15e4f8b9c2a8e8090ed9810/portal-container/65bdc7f43e11433b8f17683f96c7e626.png # YOUR IMG URL
      charset: UTF-8
      subject: 'PaaS-TA User Potal 인증메일'
      createUrl: authcreate
      expiredUrl: authreset
      inviteUrl: inviteorg
paasta:
  portal:
    api:
      authorization:
        base64: Basic YWRtaW46b3BlbnBhYXN0YQ==
      zuulUrl:
        cfapi: http://XXX.XXX.XXX.XXX:2225/portalapi #YOUR GATEWAY SERVICE DEV SETTING(ACTIVE INFORMATION)
        commonapi: http://XXX.XXX.XXX.XXX:2225/commonapi #YOUR GATEWAY SERVICE DEV SETTING(ACTIVE INFORMATION)
        storageapi: http://XXX.XXX.XXX.XXX:2225/storageapi #YOUR GATEWAY SERVICE DEV SETTING(ACTIVE INFORMATION)
    storageapi:
      type: swift


# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://XXX.XXX.XXX.XXX:2221/eureka/ #YOUR EUREKA SERVICE DEV SETTING(ACTIVE INFORMATION)
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10

logging:
  level:
    ROOT: INFO
  file:
    path: classpath:logback-spring.xml
    name: logs/application.log
